language: objective-c
osx_image: xcode7.3
xcode_project: Altimeter.xcodeproj
xcode_scheme: Altimeter
xcode_sdk: iphonesimulator9.3

script:
- xcodebuild -scheme Altimeter -project Altimeter.xcodeproj -sdk iphonesimulator build test
